name: Publish Site

on:
  push:
    branches:
    - master
    paths:
    - public/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Zedritsch/Zedritsch.github.io@master
      env:
        REPO: self
        BRANCH: pages
        FOLDER: public
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}